#!/usr/bin/env python3

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt   
from mpl_toolkits.basemap import Basemap

# set font to Arial
import matplotlib as mpl
mpl.rc('font',family='Arial')

# datasets can be found in accompanying Zenodo repository
actual_areas = np.load('actual_areas.npy')
tmax_amjjas2_z = np.load('tmax_amjjas2_z.npy')
      
tvec = np.reshape(tmax_amjjas2_z,(15372,11392))

# calculate extents of grid cells with 1.5, 2, 2.5, 3, 3.5, and 4 sigma Tmax anomalies
extent15sigma = np.empty(15372)
for k in tqdm(range(15372)):
    day = tvec[k,:]
    x1 = np.where(day>=1.5)[0]
    x2 = actual_areas[x1]
    extent15sigma[k] = np.sum(x2)/2618551

extent2sigma = np.empty(15372)
for k in tqdm(range(15372)):
    day = tvec[k,:]
    x1 = np.where(day>=2)[0]
    x2 = actual_areas[x1]
    extent2sigma[k] = np.sum(x2)/2618551
    
extent25sigma = np.empty(15372)
for k in tqdm(range(15372)):
    day = tvec[k,:]
    x1 = np.where(day>=2.5)[0]
    x2 = actual_areas[x1]
    extent25sigma[k] = np.sum(x2)/2618551
    
extent3sigma = np.empty(15372)
for k in tqdm(range(15372)):
    day = tvec[k,:]
    x1 = np.where(day>=3)[0]
    x2 = actual_areas[x1]
    extent3sigma[k] = np.sum(x2)/2618551

extent35sigma = np.empty(15372)
for k in tqdm(range(15372)):
    day = tvec[k,:]
    x1 = np.where(day>=3.5)[0]
    x2 = actual_areas[x1]
    extent35sigma[k] = np.sum(x2)/2618551    

extent4sigma = np.empty(15372)
for k in tqdm(range(15372)):
    day = tvec[k,:]
    x1 = np.where(day>=4)[0]
    x2 = actual_areas[x1]
    extent4sigma[k] = np.sum(x2)/2618551    

dates = pd.date_range(start='1/1/1940', end='12/31/2023')
dates = dates[~((dates.month == 2) & (dates.day == 29))] # index takes into account that I removed leap days
dates = pd.DataFrame(dates)
dates['month'] = pd.to_datetime(dates.iloc[:,0]).dt.month
dates = dates[dates.month.isin([4,5,6,7,8,9])]
dates.drop(columns='month',inplace=True)
dates.rename(columns={0:'date'}, inplace=True)
dates = dates.reset_index()

dates['>1.5 sd'] = extent15sigma
dates['>2 sd'] = extent2sigma
dates['>2.5 sd'] = extent25sigma
dates['>3 sd'] = extent3sigma
dates['>3.5 sd'] = extent35sigma
dates['>4 sd'] = extent4sigma
   
var = tmax_amjjas2_z[15269,:,:] # day 15269 corresponds to 6/20/2023 (out of 15372 days in April-September 1940-2023)
var = np.where(var>=2,1,np.nan)

lat = np.arange(14.75,36.76,0.25)
lon = np.arange(-118.5,-86.74,0.25)
lon, lat = np.meshgrid(lon, lat)

plt.figure(figsize=(10, 8))
m = Basemap(projection='lcc', area_thresh=10000, resolution='l',
            width=3.3E6, height=3.3E6,
            lat_0=25, lon_0=-102)
m.fillcontinents(color='white',lake_color='white',alpha=1,zorder=0)
m.drawstates(linewidth=0.5,linestyle='solid',color='k')
m.drawcountries(linewidth=0.5,linestyle='solid',color='k')
m.drawcoastlines(color='black')
m.pcolormesh(lon, lat, var, latlon=True, cmap=plt.cm.get_cmap('Reds'))
plt.title('Grid cells >2 sd Tmax on June 20, 2023', size=20)
plt.clim(0,1)      
m.readshapefile('texas_mexico',name='oceans',color='b',linewidth=2)

# create Fig 6b
var = tmax_amjjas2_z[14387,:] # day 14387 corresponds to 7/23/2018 (out of 15372 days in April-September 1940-2023)
var = np.where(var>=2,1,np.nan)

lat = np.arange(14.75,36.76,0.25)
lon = np.arange(-118.5,-86.74,0.25)
lon, lat = np.meshgrid(lon, lat)

plt.figure(figsize=(10, 8))
m = Basemap(projection='lcc', area_thresh=10000, resolution='l',
            width=3.3E6, height=3.3E6,
            lat_0=25, lon_0=-102)
m.fillcontinents(color='white',lake_color='white',alpha=1,zorder=0)
m.drawstates(linewidth=0.5,linestyle='solid',color='k')
m.drawcountries(linewidth=0.5,linestyle='solid',color='k')
m.drawcoastlines(color='black')
m.pcolormesh(lon, lat, var, latlon=True, cmap=plt.cm.get_cmap('Reds'))
plt.title('Grid cells >2 sd Tmax on July 23, 2018', size=20)
plt.clim(0,1)      
m.readshapefile('texas_mexico',name='oceans',color='b',linewidth=2)
