#!/usr/bin/env python3

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt   
from mpl_toolkits.basemap import Basemap

# set font to Arial
import matplotlib as mpl
mpl.rc('font',family='Arial')

# datasets can be found in accompanying Zenodo repository
tmax_amjjas2_z = np.load('tmax_amjjas2_z.npy')
  
tvec = np.reshape(tmax_amjjas2_z,(15372,11392))

# find number of grid cells in domain
maxs = np.nanmax(tvec,axis=0)
np.nanmax(maxs)
np.nanmin(maxs)
np.size(np.where(maxs>0)) # 3792 grid cells

idx_max = np.empty(11392)
idx_max[:] = np.nan
for k in tqdm(range(11392)):
    cell = tvec[:,k]
    cell[15280:] = np.nan
    if np.nanmax(cell) > 0:
        cell = cell[~np.isnan(cell)]
        idx_max[k] = np.argmax(cell)

jun23_highest = np.where((idx_max>=15250)&(idx_max<=15279),1,0) 
jun23_highest = np.where(jun23_highest==0,np.nan,jun23_highest)
        
var = np.reshape(jun23_highest,(89,128))

lat = np.arange(14.75,36.76,0.25)
lon = np.arange(-118.5,-86.74,0.25)
lon, lat = np.meshgrid(lon, lat)

plt.figure(figsize=(10, 8))
m = Basemap(projection='lcc', area_thresh=10000, resolution='l',
            width=3.3E6, height=3.3E6,
            lat_0=25, lon_0=-102)
m.fillcontinents(color='white',lake_color='white',alpha=1,zorder=0)
m.drawstates(linewidth=0.5,linestyle='solid',color='k')
m.drawcountries(linewidth=0.5,linestyle='solid',color='k')
m.drawcoastlines(color='black')
m.pcolormesh(lon, lat, var, latlon=True, cmap=plt.cm.get_cmap('Reds'))
plt.title('Grid cells that recorded highest daily Tmax z-scores in June 2023 \n (compared to all days in April-September 1940-2023)', size=20)
plt.clim(0,1)      
m.readshapefile('texas_mexico',name='null',color='b',linewidth=2)
