#!/usr/bin/env python3

'''
This code downloads Z500 data between 5-45N across the entire NHEM (-180 to 179 lon).
This is used to calculate detrended Z500 in latitudinal bands. 
'''
  
import cdsapi
import numpy as np
import sys

year = int(sys.argv[2]) + 1940

months = list(np.arange(1,13,1))
months = list(map(str, months))
days = list(np.arange(1,32,1))
days = list(map(str, days))
times = list(np.arange(0,24,1))
times = list(map(str, times))

c = cdsapi.Client()
c.retrieve('reanalysis-era5-pressure-levels', {
        'product_type'  : 'reanalysis',
        'variable'      : 'geopotential',
        'pressure_level': '500',
        'year'          : str(year),
        'month'         : months,
        'day'           : days,
        'time'          : times,
        'area'          : [45, -180, 5, 179],
        'grid'          : [0.25, 0.25],
        'format'        : 'netcdf'
    }, f'z500_global_{year}.nc')
