#!/usr/bin/env python3

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt   

# set font to Arial
import matplotlib as mpl
mpl.rc('font',family='Arial')

# datasets can be found in accompanying Zenodo repository

tmax_z_normed = np.load('tmax_z_normed2.npy') # domain-averaged Tmax standardized anomalies
vals = tmax_z_normed

dates = pd.date_range(start='1/1/1940', end='12/31/2023')
dates = pd.DataFrame(dates)
dates['month'] = pd.to_datetime(dates.iloc[:,0]).dt.month
dates['year'] = pd.to_datetime(dates.iloc[:,0]).dt.year
dates = dates[dates.month.isin([4,5,6,7,8,9])]
dates.reset_index(inplace=True)

vals2 = vals[15250:15280] # subset to June 2023

# calculate daily records in June (1940-2022)
dates = dates[dates.month == 6]
dates = dates[~(dates.year == 2023)]
vals3 = vals[dates.index.values]
table = np.reshape(vals3,(83,30))

daily_max = []
for k in range(30):
    day = table[:,k]
    daily_max.append(np.max(day))

sm_z_normed = np.load('sm_z_normed2.npy') # domain-averaged SM standardized anomalies
valz = sm_z_normed

dates = pd.date_range(start='1/1/1940', end='12/31/2023')
dates = pd.DataFrame(dates)
dates['month'] = pd.to_datetime(dates.iloc[:,0]).dt.month
dates['year'] = pd.to_datetime(dates.iloc[:,0]).dt.year
dates = dates[dates.month.isin([4,5,6,7,8,9])]
dates.reset_index(inplace=True)

valz2 = valz[15250:15280] # subset to June 2023

# calculate daily records in June (1940-2022)
dates = dates[dates.month == 6]
dates = dates[~(dates.year == 2023)]
valz3 = valz[dates.index.values]
table = np.reshape(valz3,(83,30))

daily_max2 = []
for k in range(30):
    day = table[:,k]
    daily_max2.append(np.min(day)) # switched max to min for soil moisture

valz2 = valz2 * -1
daily_max2 = np.array(daily_max2) * -1

z500_z_normed = np.load('z500_z_normed.npy') # domain-averaged Z500 standardized anomalies
valss = np.nanmean(z500_z_normed,axis=1)

dates = pd.date_range(start='1/1/1940', end='12/31/2023')
dates = pd.DataFrame(dates)
dates['month'] = pd.to_datetime(dates.iloc[:,0]).dt.month
dates['year'] = pd.to_datetime(dates.iloc[:,0]).dt.year
dates = dates[dates.month.isin([4,5,6,7,8,9])]
dates.reset_index(inplace=True)

valss2 = valss[15250:15280] # subset to June 2023

# calculate daily records in June (1940-2022)
dates = dates[dates.month == 6]
dates = dates[~(dates.year == 2023)]
valss3 = valss[dates.index.values]
table = np.reshape(valss3,(83,30))

daily_max3 = []
for k in range(30):
    day = table[:,k]
    daily_max3.append(np.max(day))

fig = plt.figure(figsize=(8,6))
plt.plot(vals2,'-o', color='orangered')
plt.plot(daily_max,'--', color='orangered', lw=1)
plt.plot(valz2,'-o', color='tab:brown')
plt.plot(daily_max2,'--', color='tab:brown', lw=1)
plt.plot(valss2,'-o', color='k')
plt.plot(daily_max3,'--', color='k', lw=1)
plt.scatter(19,vals2[19],marker='*',c='w',edgecolor='k',s=300)
plt.scatter(20,vals2[20],marker='*',c='w',edgecolor='k',s=300)
plt.scatter(19,valz2[19],marker='*',c='w',edgecolor='k',s=300)
plt.scatter(20,valz2[20],marker='*',c='w',edgecolor='k',s=300)
plt.scatter(21,valz2[21],marker='*',c='w',edgecolor='k',s=300)
#plt.grid(linewidth=0.5, color='0.5', alpha=0.5, linestyle='-.')
plt.xticks([0,9,19,29], ('June 1','June 10','June 20','June 30'), fontsize = 13)
plt.yticks(np.arange(-2,4.01,0.5), fontsize=13)
plt.axhline(y=0,color='0.5',linestyle='--')
plt.axvline(x=14,color='0.5',linestyle='--')
plt.axvline(x=27,color='0.5',linestyle='--')
plt.ylabel('Standardized anomaly', fontsize = 18)

# re-plot this on extended y-axis to make legend
fig = plt.figure(figsize=(8,6))
#plt.plot(vals1,'--', color='tab:brown')
plt.plot(vals2,'-o', color='orangered')
plt.plot(daily_max,'--', color='orangered', lw=1)
plt.plot(valz2,'-o', color='tab:brown')
plt.plot(daily_max2,'--', color='tab:brown', lw=1)
plt.plot(valss2,'-o', color='k')
plt.plot(daily_max3,'--', color='k', lw=1)
plt.yticks(np.arange(-5,4.01,0.5), fontsize=13)
l = plt.legend(['June 2023 Tmax',
            '1940-2022 Tmax daily records',
            'June 2023 SM (negative)',
            '1940-2022 SM daily records (negative)',
            'June 2023 Z500 z-score',
            '1940-2022 Z500 z-score daily records'], 
            loc='lower right', fontsize=15)
for text in l.get_texts():
    s = str(text)
    print(s)
    if s[26] == '\'':
        text.set_color('orangered')
    elif s[27] == 'd':
        text.set_color('orangered')
    elif s[25] == '(':
        text.set_color('tab:brown')
    elif s[25] == 'd':
        text.set_color('tab:brown')
    elif s[34] == '\'':
        text.set_color('k')
    elif s[35] == 'd':
        text.set_color('k')
