#!/usr/bin/env python3

# batch script for kamiak, which uses a job array to launch all 15,372 daily matching scripts in parallel (in batches of 187) 
# all batches finish executign in approx. 1h 40m
# following this, the script to concat the daily corr files into single array runs for another approx 3h 15m

import numpy as np
import sys

def mean2(x):
    y = np.sum(x) / np.size(x)
    return y

def corr2(a,b): # define function to compute 2D pattern correlation
    a = a - mean2(a)
    b = b - mean2(b)

    r = (a*b).sum() / np.sqrt((a*a).sum() * (b*b).sum())
    return r

# this the Z500 standardized, detrended anomalies that are subset to the smaller rectangle used for ciculation matching
zvec = np.load('zvec_smaller.npy')

idx = int(sys.argv[2])

target = zvec[idx,:]
corrs = np.empty(15372)
for k in range(15372):
    day = zvec[k,:]
    corrs[k] = corr2(target,day)

np.save(f'corrs{idx}',corrs)
