#!/usr/bin/env python3

'''
Merge the 1940-2022 and 2023 Z500 arrays into a single array covering 1940-2023, and remove leap dates.
'''

import numpy as np
import pandas as pd

var1 = np.load('z500_1940_2022.npy')
var2 = np.load('z500_2023.npy')

z500 = np.concatenate([var1,var2],axis=0)
z500 = z500/9.80665

dates = pd.date_range(start='1/1/1940', end='12/31/2023')
dates = pd.DataFrame(dates)
dates['month'] = pd.to_datetime(dates.iloc[:,0]).dt.month
dates['day'] = pd.to_datetime(dates.iloc[:,0]).dt.day
dates = dates[~((dates.month == 2) & (dates.day == 29))]
idx = dates.index.values

z500_noleap = z500[idx,:]

np.save('z500_all',z500_noleap.astype('float32'))
